module.exports = {
	author: "ACLU",
	description: "A website for the ACLU emails.",
	environment: process.env.ELEVENTY_ENV,
	fbLogo: "https://media.sailthru.com/64d/1k8/3/f/65f481e7a6012.png",
	igLogo: "https://media.sailthru.com/64d/1k8/3/f/65f481e78c693.png",
	logo: "https://media.sailthru.com/64p/1k3/9/f/5d7ec2cd22763.png",
	privacy: "https://www.aclu.org/about/privacy/statement/?redirect=american-civil-liberties-union-privacy-statement",
	title: "ACLU Email",
	twitter: "aclu",
	xLogo: "https://media.sailthru.com/64d/1k8/3/f/65f4803d78db4.png",
	threadsLogo: "https://media.sailthru.com/64d/1k8/c/u/6772ff5288341.png",
	unsub: "https://action.aclu.org/preference-center/aclu-action-national-email-preference",
	url: "https://aclu.org",
};
